### ISSUE TITLE
Pre-trained model files

### ISSUE THREAD

**Issue by ma-siddiqui** [mmaaz60/mvits_for_class_agnostic_od#13]
It's really a great work by great researchers. May I request for your pretrained weight files, particularly lvis, objects365.

**Comment by mmaaz60** [comment]
Hi @ma-siddiqui,

Thank you for your interest in our work. There is no specific model for LVIS or Objects365. Our MAVL model can generate class-agnostic boxes for both of these datasets using intuitive language queries such as `all objects`, `all entities`, etc.

The MAVL weights can be downloaded from [this link](https://drive.google.com/drive/folders/1TLge0mNiL2pV2VygLqKqc1FbEiJEQzJt?usp=sharing). Note that MDef-DETR is the same as MAVL. 

You can follow [these instructions](https://github.com/mmaaz60/mvits_for_class_agnostic_od/issues/4#issuecomment-988573984) to generate proposals on LVIS and Objects365 using a given text query. Further, the instructions at [evaluation_readme](https://github.com/mmaaz60/mvits_for_class_agnostic_od/blob/main/evaluation/class_agnostic_od/README.md) can be used for evaluating class-agnostic performance on LVIS and Objects365. Note that both LVIS and Objects365 provide annotations in COCO format, so the process for evaluation would be same as COCO.

Currently, we don't have step-by-step instructions and the custom links to download the LVIS and Objects365 datasets and you are requested to download them from their official websites, that may take some time.

Please let me know if you face any issues. Good Luck!

**Comment by ma-siddiqui** [comment]
Thank you dear Maaz for the detailed information.

**Comment by 22wei22** [comment]
> Hi @mmaaz60 
> 
> Thank you for your interest in our work. There is no specific model for LVIS or Objects365. Our MAVL model can generate class-agnostic boxes for both of these datasets using intuitive language queries such as `all objects`, `all entities`, etc.
> 
> The MAVL weights can be downloaded from [this link](https://drive.google.com/drive/folders/1TLge0mNiL2pV2VygLqKqc1FbEiJEQzJt?usp=sharing). Note that MDef-DETR is the same as MAVL.
> 
> You can follow [these instructions](https://github.com/mmaaz60/mvits_for_class_agnostic_od/issues/4#issuecomment-988573984) to generate proposals on LVIS and Objects365 using a given text query. Further, the instructions at [evaluation_readme](https://github.com/mmaaz60/mvits_for_class_agnostic_od/blob/main/evaluation/class_agnostic_od/README.md) can be used for evaluating class-agnostic performance on LVIS and Objects365. Note that both LVIS and Objects365 provide annotations in COCO format, so the process for evaluation would be same as COCO.
> 
> Currently, we don't have step-by-step instructions and the custom links to download the LVIS and Objects365 datasets and you are requested to download them from their official websites, that may take some time.
> 
> Please let me know if you face any issues. Good Luck!

I am Chinese. I fail to download pretrained model MDef_DETR_r101_epoch20.pth. Could you send me the model to my email 1334637558@qq.com
