### ISSUE TITLE
Loading checkpoints for inference

### ISSUE THREAD

**Issue by KaleemW** [mmaaz60/mvits_for_class_agnostic_od#14]
Which checkpoints in drive link you provided will load correctly in default MDefDETR model without any errors? Im getting missing/unexpected keys errors.

**Comment by mmaaz60** [comment]
Hi @KaleemW,

Please try loading [MDef_DETR_r101_epoch20.pth](https://drive.google.com/file/d/1eYMmOLx3wNX4u5vGOWgVTwr0vLH1MyIr/view?usp=sharing) checkpoints. If you will still get an error then please post the full error message along with the process you are following for loading the weights here. I hope it will be helpful. Thank you

**Comment by projectz-ali** [comment]
Thanks a lot. It worked. Just wanted to know one last thing that is there a cpu implementation available for this project. I ran successfully with cuda but without cuda it doesnt compile MSDA...

**Comment by KaleemW** [comment]
Thanks a lot. It worked. Just wanted to know one last thing that is there a cpu implementation available for this project. I ran successfully with cuda but without cuda it doesnt compile MSDA...

**Comment by mmaaz60** [comment]
> Thanks a lot. It worked. Just wanted to know one last thing that is there a cpu implementation available for this project. I ran successfully with cuda but without cuda it doesnt compile MSDA...

Hi @KaleemW,

Unfortunately, only GPU implementation is available at the moment.

**Comment by KaleemW** [comment]
Ok Sir! Thank You for your help.

**Comment by Edwardmark** [comment]
@mmaaz60 hi could you tell me what is the inference speed of your model? and how to do batch inference to improve the efficiency? Thanks.

**Comment by mmaaz60** [comment]
Hi @Edwardmark,

Thank you for your interest in our work. Please refer to the Table 10 of our [paper](https://arxiv.org/pdf/2111.11430.pdf) for inference speed. Further, the batch inference implementation is available at [modulated_detection.py](https://github.com/mmaaz60/mvits_for_class_agnostic_od/blob/ae561b09a912dd1743f1d4f92971e85ced5b49d2/inference/modulated_detection.py#L111).

I hope it will help. Thank You.
