### ISSUE TITLE
pretrain data download

### ISSUE THREAD

**Issue by zhouxingguang** [mmaaz60/mvits_for_class_agnostic_od#16]
if is it possible to split pretrain data into multiple seperate zip files。
I download data from google drive : https://drive.google.com/drive/folders/1-3kAsyZIVFbNelRXrF93Y5tMgOypv2jV
i cannot download this data because of google drive time limit(less than 1 hours) and my limit network bandwidth。

**Comment by mmaaz60** [comment]
Hi @zhouxingguang,

Please download the data in small chunks from https://drive.google.com/drive/folders/1YiudOuP9hTFEVsK_ntClWHljnc35W-WM?usp=share_link

Note that you have to merge all the zip files before unzipping. I hope it will be helpful. Thanks
