### ISSUE TITLE
how to generate 'tokens_positive'  ann from detector dataset like object365?

### ISSUE THREAD

**Issue by zhouxingguang** [mmaaz60/mvits_for_class_agnostic_od#17]
I found 'tokens_positive' was used in your ann file. could you please release the code of how to process detect data like coco to get the 'tokens_positive' ann results?

**Comment by mmaaz60** [comment]
Hi @zhouxingguang,

Apologies for the delayed response. Following [MDETR](https://arxiv.org/pdf/2104.12763.pdf), we use annotations from the referring expressions datasets (RefCOCO, RefCOCO+, and RefCOCOg [36]) for COCO images. Please refer to the implementation details section on page 5 of our [paper](https://arxiv.org/pdf/2111.11430.pdf) and Appendix C in [MDETR](https://arxiv.org/pdf/2104.12763.pdf) for more details. Also the corresponding scripts to prepare the datasets are available at the MDETR official repo at https://github.com/ashkamath/mdetr/tree/main/scripts/pre-training.

I hope this would be helpful. Do let me know if you have any questions. Thanks
