### ISSUE TITLE
one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by xushilin1** [mmaaz60/mvits_for_class_agnostic_od#20]
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.LongTensor [2, 20]] is at version 3; expected version 2 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

This error will terminate the training procedure when training mdef_detr using the PyTorch environment as you advise(torch==1.8.0+cu111).

And I found the variables of 'transformer.text_encoder.pooler.dense.weight' does not have grad. This may be the main reason for this error.

**Comment by mmaaz60** [comment]
Hi @xushilin1,

Thank you for your interest in our work. Could you please provide some further details to debug the issue that you are facing? Specifically,
1. `transformers` version. Make sure you are using `transformers==4.5.1`.
2. The exact commit from `https://github.com/mmaaz60/mdef_detr` repository.
3. The hardware that you are running on. Are you training on a single GPU?
4. Are you using the same CUDA version (e.g. CUDA 11.1) for compiling the Deformable Attention module?
5. The command to run the training.

Thank you for your patience. Looking forward to your response.

**Comment by xushilin1** [comment]
Thanks for your reply. 

I tried `transformers==4.5.1` and the error was solved.
