### ISSUE TITLE
How long the training takes?

### ISSUE THREAD

**Issue by lxtGH** [mmaaz60/mvits_for_class_agnostic_od#21]
HI! @mmaaz60 Thanks for your opensource this project.  I wonder how long the training procedure takes?  What kind of device you yse?

**Comment by mmaaz60** [comment]
Hi @lxtGH,

Thank you for your interest in our work. We train MAVL model on approx. 1.3 M aligned image-text pairs. The dataset is the same as used in [MDETR](https://arxiv.org/abs/2104.12763). The training took almost 3 days on 32 V100 GPUs. Following this the model is evaluated on diverse datasets (Table 1 & 2) for class-agnostic object detection without any finetuning.
