### ISSUE TITLE
Which checkpoint to use to reproduce Object Centric OVD results?

### ISSUE THREAD

**Issue by alexey-chaykin** [mmaaz60/mvits_for_class_agnostic_od#22]
Thank you for sharing your work. Could you please clarify the name of the checkpoint to be used for regions gathering for OC-OVD?

**Comment by mmaaz60** [comment]
Hi @alexey-chaykin,

Thank you for your interest in our work. We use [MDef_DETR_r101_epoch20.pth](https://drive.google.com/file/d/1eYMmOLx3wNX4u5vGOWgVTwr0vLH1MyIr/view?usp=share_link) checkpoints for generating regions for OVD. Note that this is the same model with name as MAVL in our [paper](https://arxiv.org/pdf/2111.11430.pdf). Please let me know if you have any questions. Thanks

**Comment by alexey-chaykin** [comment]
Thanks
