### ISSUE TITLE
Confusion about the number of ORE test dataset

### ISSUE THREAD

**Issue by dengyuhai** [mmaaz60/mvits_for_class_agnostic_od#25]
Hi @mmaaz60 

Thanks for your great work!

 I found that the number of test dataset is 9119 in your log.txt file for ORE test procedures.
![2A_BIK88TI1A%FWTJMRBV{H](https://user-images.githubusercontent.com/108168301/227208518-2e772518-2ec2-41d1-8041-74521e5feaf0.png)

 But in the current ORE repository, the number of test dataset is 10246. 
![S8 N7M6ESMF0~RCVD_WCXIS](https://user-images.githubusercontent.com/108168301/227208640-855ce558-500c-4c34-a0c7-5617e18508fe.png)

Could you please provide me with your ORE test dataset division?
Thanks again！

**Comment by mmaaz60** [comment]
Hi @Dyuhai,

Thank You for your interest in our work. While experimenting with ORE, we found that there are some duplicate images in the provided `all_task_test.txt`. After removing the duplicates, the remaining images count to 9119 only.

I am attaching the updated `all_task_test.t
[all_task_test_duplicates_removed.txt](https://github.com/mmaaz60/mvits_for_class_agnostic_od/files/11068599/all_task_test_duplicates_removed.txt)
xt` file along with the sample code to remove the duplicates for your reference. I hope it will help.

[all_task_test.zip](https://github.com/mmaaz60/mvits_for_class_agnostic_od/files/11068601/all_task_test.zip)
