### ISSUE TITLE
Possibility to Change the Text Encoder?

### ISSUE THREAD

**Issue by mcairlangga2** [mmaaz60/mvits_for_class_agnostic_od#27]
Dear Authors,
Thank you for the great work.

I want to ask a question. Is it possible to change the text encoder to other models such as CLIP instead of using RoBERTa? Have you considered and tried another Text Encoder? If it's possible how to change it in the code? 

Thank you!

**Comment by mmaaz60** [comment]
Hi @mcairlangga2,

Yes, it is possible however we did not consider this research direction. With the recent advancements in NLP & Vision-Language modeling, it will be a worth exploring problem. 

As per the implementation is concerned, it would be replacing RoberTa at [this file](https://github.com/mmaaz60/mvits_for_class_agnostic_od/blob/ae561b09a912dd1743f1d4f92971e85ced5b49d2/models/mdef_detr/deformable_transformer.py#L12) with CLIP or other text decoder. Good Luck
