### ISSUE TITLE
Applications on custom datasets are expected

### ISSUE THREAD

**Issue by 834799106** [mmaaz60/mvits_for_class_agnostic_od#3]
Now I'm not sure what data format I need to prepare to train this method

**Comment by mmaaz60** [comment]
Hi @834799106,

Thank you for your interest in our work. Currently, we have only released the evaluation code along with the pre-trained models. We will be releasing the training instructions/code in a month or so.

Furthermore, as shown in Table 2 of the [paper](https://arxiv.org/abs/2111.11430), MDef-DETR works well on many off-the-shelf datasets. You can try generating class-agnostic detections on your custom dataset and it's likely that you will get reasonable results.

**Comment by nikky4D** [comment]
Hi @mmaaz60 , is there any update on the training code status?

**Comment by mmaaz60** [comment]
> Hi @mmaaz60 , is there any update on the training code status?

Hi @nikky4D, we are planning to release the code by the end of this month. Thank you for your patience and stay tuned!

**Comment by nikky4D** [comment]
Any update on the training code status

**Comment by mmaaz60** [comment]
> Any update on the training code status

Hi @nikky4D, the code is now released. Please have a look at https://github.com/mmaaz60/mvits_for_class_agnostic_od/releases/tag/v1.0
